variables:
  #CI_DEBUG_TRACE: "true"
  #GET_SOURCES_ATTEMPTS: 10
  #ARTIFACT_DOWNLOAD_ATTEMPTS: 10
  #RESTORE_CACHE_ATTEMPTS: 10
  #GLOBAL_CI_VARIABLE: "global_ci_value"
  #http_proxy: "http://proxyout.lanl.gov:8080"
  #https_proxy: "http://proxyout.lanl.gov:8080"
  #ftp_proxy: "http://proxyout.lanl.gov:8080"
  #no_proxy: "lanl.gov"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  CCACHE_UMASK: 000
  CXXFLAGS: "-Wno-deprecated-declarations"
  GASNET_BACKTRACE: 1
  FLECSALE_DISTRO: "centOS"
  FLECSALE_CI_JOB_NAME_NOSTAGE: ${CI_JOB_NAME#*:}
  FLECSALE_MPI_PROVIDER: ""
  FLECSALE_MPICH_VERSION: "3.2.1"
  FLECSALE_MPICH_SPEC: "+slurm"
  FLECSALE_OPENMPI_VERSION: "3.1.4"
  #FLECSALE_OPENMPI_SPEC: "+pmi+legacylaunchers+thread_multiple schedulers=slurm"
  FLECSALE_OPENMPI_SPEC: "+pmi+legacylaunchers+thread_multiple"
  FLECSALE_INTEL_VERSION: "19.0.2"
  FLECSALE_CLANG_VERSION: "8.0.1"
  FLECSALE_GCC_VERSION: "8.3.0"
  FLECSALE_PYTHON_VERSION: "3.5.1"
  FLECSALE_SPACK_SPEC: "flecsalemm-deps%gcc@${FLECSALE_GCC_VERSION} backend=${FLECSALE_RUNTIME}"
  FLECSALE_SPACK_HASH: "a9b64bcaf128eb8ab19081328d2a19035ca60e0c"
